### ISSUE TITLE
dynmap reload resets changes in dynmap-plotmes config

### ISSUE THREAD

**Issue by EvilOlaf** [WorldCretornica/Dynmap-PlotMe#3]
I do not know if this behavior is wanted or not, I will post it anyway.

If you chance something at the config file of dynmap-plotme and do a /dynmap reload the config chances are being reset. In order to activate any chances there you need to reload or (much better) restart the server.

**Comment by MarkusAV** [comment]
Any errors in your console when reloading dynmap-plotme?

**Comment by EvilOlaf** [comment]
I did not know that dynmap-plotme can be reloaded without reloading dynmap as itself. 
How do I do that? 

If I do /dynmap reload there were no error messages, just the usual stuff: Unloading etc... Loading...  I can post a complete output later.
